[package]
name = "sx13xx-conf"
version = "0.1.0"
authors = ["Louis Thiery <thiery.louis@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "*", features = ["derive"]}
serde_json = "*"
structopt = "0.3"