[package]
name = "regions"
version = "0.1.1"
authors = ["Louis Thiery <thiery.louis@gmail.com>"]
edition = "2018"

keywords = ["semtech", "lora", "helium"]
license = "Apache-2.0"

[dependencies]
strum = "0.20"
strum_macros = "0.20"
